version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: workshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: .
    ports:
      - "8080:8080"

volumes:
  mysql_data:
