spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workshop
    username: user
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema

springdoc:
  swagger-ui:
    path: /docs
    title: Workshop REST API